language: python
python:
  - "3.5"
  CODECOV_TOKEN="11ed90e0-5105-4837-8f86-b0e69a44fde4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest


# command to run tests
script: pytest

after_success:
  - coveralls
  - codecov
